clear all;
data = imageDatastore(                  ...
        fullfile('../data/CASIA_gray_15'), ...
        'IncludeSubfolders',            ...
        true,                           ...
        'LabelSource'                   ...
        ,'foldernames');

trainCNN(50,9284,15);
